### ISSUE TITLE
请问，有npm的包吗？

### ISSUE THREAD

**Issue by Timnny** [ff755/vue-kindeditor#1]
请问，有npm的包吗？

**Comment by ff755** [comment]
`yarn add vue-kindeditor`

有了

**Comment by Timnny** [comment]
大哥，有没有详细的例子，我们看明白怎么用。

**Comment by ff755** [comment]
@Timnny 等等写个

**Comment by ff755** [comment]
@Timnny https://github.com/ff755/vue-kindedtior-demo.git

**Comment by Timnny** [comment]
大哥，我在调用上传图片是报错了，
function _iframeDoc(iframe) {
	iframe = _get(iframe);
	return iframe.contentDocument || iframe.contentWindow.document;
}
这个函数的iframe.contentDocument报错了，您能帮我看下吗？

**Comment by ff755** [comment]
@Timnny  稍等会儿 吃了饭帮你看

**Comment by ff755** [comment]
@Timnny 我这得不到错误 把你代码贴出来看看
`
<editor id="editor_id" height="500px" width="700px" :content="editorText"
            uploadJson="/api/up"
            pluginsPath="/static/kindeditor/plugins/"
            :loadStyleMode="false"
            @on-content-change="onContentChange"></editor>
`
uploadJson上传地址
//成功时
{
        "error" : 0,
        "url" : "图片的url"
}
//失败时
{
        "error" : 1,
        "message" : "错误信息"
}

**Comment by PingChou** [comment]
上传图片的请求头怎么设置啊
