### ISSUE TITLE
最新版本0.4组件注册不成功

### ISSUE THREAD

**Issue by kakercoco** [ff755/vue-kindeditor#12]
[Vue warn]: Unknown custom element: <editor> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by ff755** [comment]
@kakercoco 确实存在这样的问题 先使用前面的版本。稍后处理好了 留言给你

**Comment by ff755** [comment]
@kakercoco 更新到0.4.5版本使用，有问题在此留言
