### ISSUE TITLE
ie9 问题

### ISSUE THREAD

**Issue by byxxw** [ff755/vue-kindeditor#18]
IE9下可以正常渲染，
在初始化有内容时，编辑器无法输入内容，初始化的内容也不展示
有时HTML代码下有内容，切换非HTML后就没有内容了
![image](https://user-images.githubusercontent.com/3401067/87498535-8e18d500-c68a-11ea-8ddb-139b8595ec9d.png)

无内容：
![image](https://user-images.githubusercontent.com/3401067/87498543-9709a680-c68a-11ea-861c-702c9ce184ae.png)

**Comment by ff755** [comment]
ie9不兼容 根据错误去判断是什么引起的 

本地没ie9 测不了什么问题
