### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by chordmo** [ff755/vue-kindeditor#4]
可以运行项目 npm run dev
但是是发布的时候 npm run build报错了

<img width="992" alt="wx20170718-012745 2x" src="https://user-images.githubusercontent.com/8435726/28282490-2d50acd8-6b5d-11e7-8e70-5448e79d5c8e.png">

**Comment by ff755** [comment]
我这边也遇到这个问题，我找找原因

**Comment by ff755** [comment]
升级下0.2.1版本 重新build试试
