### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by GreatSir** [ff755/vue-kindeditor#5]
ERROR in ./~/vue-kindeditor/src/plugins/vue-kindeditor.js
Module not found: Error: Can't resolve '../components/KindEditors' in '/data/www/element-starter-master/node_modules/vue-kindeditor/src/plugins'
 @ ./~/vue-kindeditor/src/plugins/vue-kindeditor.js 1:0-50
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8010 webpack/hot/dev-server ./src/main.js

**Comment by ff755** [comment]
yarn 把包更新下试试，我这边没出现这个问题
