### ISSUE TITLE
数据更新后，富文本编辑框不能编辑的bug有解决的思路吗？

### ISSUE THREAD

**Issue by HankBass** [ff755/vue-kindeditor#6]

**Comment by ff755** [comment]
有错误提示吗

**Comment by wroy1005** [comment]
Cannot read property 'getSelection' of null"

**Comment by ff755** [comment]
@wroy1005 我这本地用 vue-cli 建的项目 使用 vue-router 切换路由编辑正常

**Comment by wroy1005** [comment]
@ff755 刚试了一下，切换路由使用keep-alive时，会出现不能编辑的问题。

**Comment by ff755** [comment]
晚上发布

**Comment by ff755** [comment]
@wroy1005 更新 0.3.0 试试
